name: My First Workflow

on: [push]

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
          - name: checkout Repo
            uses: actions/checkout@v6

          #- name: list files
          #  run: ls
          
          - name: run multiple commands
            run: |
              echo "my first Github Actions job"
              ls -la
              cat README.md
          
          - name: Generate ASCII artwork
            run: cowsay -f dragon "Run for Cover" >> dragon.txt
        