name: matrix-configurations
on: 
- workflow_dispatch

jobs:
    deploy:
        strategy:
            matrix:
                os: [ ubuntu-latest, ubuntu-20.04, windows-latest]
                images: [ hello-world, alpine]
                exclude:
                    - images: alpine
                      os: windows-latest
                include:
                    - images: nginx:alpine-slim
                      os: ubuntu-latest
            
        runs-on: ${{matrix.os}}
        steps:
        - name: Echo Docker Details
          timeout-minutes: 2
          run: docker info
          
        - name: Run Images
          run:  docker run ${{matrix.images}}