name: matrix-configurations
on: 
- workflow_dispatch

jobs:
    deploy:
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest]
                images: [ hello-world, alpine]
                exclude:
                    - images: alpine
                      os: windows-latest
                include:
                    - images: alpine
                      os: ubuntu-20.04
            
        runs-on: ${{matrix.os}}
        steps:
        - name: Echo Docker Details
          timeout-minutes: 1
          run: docker info
          
        - name: Run Images
          run:  docker run ${{matrix.images}}
          timeout-minutes: 2