name: Variables-Secrets-2
on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
      - 'releases/**'
      - '!feature/*'
    paths-ignore: README.md  
  
env:
    CONTAINER_REGISTRY: docker.io
    #DOCKER_USERNAME: dockerUsername
    IMAGE_NAME: github-action-nginx
jobs:
    docker:        
        runs-on: ubuntu-latest
        steps:
        - name: Docker build
          run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
          
        - name: Docker login          
          run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASS}}

        - name: Docker publish
          run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

    deploy:
        if: github.ref == 'refs/heads/main'  
        needs: docker        
        timeout-minutes: 2
        concurrency:
          group: prod_deployment
          cancel-in-progress: true  # will prioritize run on newly executed and cancel old running job; false - will wait to complete existing.
        runs-on: ubuntu-latest
        steps:
        - name: Docker run
          timeout-minutes: 1
          run: |
            echo docker run -d -p 8080:80 ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
            sleep 15s